#!/bin/sh

# From https://github.com/BurntSushi/ripgrep/blob/87b33c96c02b5d728324632956d301ef3d234f80/ci/sha256-releases

set -e

if [ $# != 1 ]; then
  echo "Usage: $(basename $0) version" >&2
  exit 1
fi
version="$1"

# Linux and Darwin builds.
for arch in x86_64; do
  for target in apple-darwin unknown-linux-musl; do
    url="https://github.com/insilica/rs-srvc/releases/download/$version/srvc-$version-$arch-$target.tar.gz"
    sha=$(curl -sfSL "$url" | sha256sum)
    echo "$version-$arch-$target $sha"
  done
done

# Source.
for ext in zip tar.gz; do
  url="https://github.com/insilica/rs-srvc/archive/$version.$ext"
  sha=$(curl -sfSL "$url" | sha256sum)
  echo "source.$ext $sha"
done
